default_platform(:android)

platform :android do
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:940046231017:android:2312d7ff69c3178c635778",
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "sa.mohammad7567@gmail.com",
        release_notes: "New build from CI",
    )
  end
end
